# Generated by Django 3.0.4 on 2020-04-11 18:33

from django.db import migrations


def populate_kinds(apps, *args):
    Kind = apps.get_model('notes', 'Kind')

    Kind.objects.bulk_create([
        Kind(slug='repair', title='Ремонт'),
        Kind(slug='service', title='Обслуживание'),
        Kind(slug='tuning', title='Тюнинг'),
        Kind(slug='untagged', title='Иные расходы'),
        Kind(slug='memo', title='Заметки'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_kinds)
    ]
